CREATE TABLE users (
    id INT unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
    google_id VARCHAR( 32 ) DEFAULT NULL,
    name VARCHAR( 32 ) NOT NULL,
    email VARCHAR( 32 ) DEFAULT NULL,
    picture VARCHAR( 64 ) DEFAULT NULL,
    password VARCHAR( 32 ) DEFAULT NULL,
    created DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE automata (
    id INT unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
    public BOOLEAN NOT NULL DEFAULT 1,
    uid INT unsigned DEFAULT NULL,
    name TEXT NOT NULL DEFAULT '',
    data MEDIUMTEXT NOT NULL DEFAULT '',
    created DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
    FOREIGN KEY (uid) REFERENCES user(id)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

-- CREATE TABLE automata_users (
--     uid INT unsigned NOT NULL,
--     aid INT unsigned NOT NULL,
--     FOREIGN KEY (uid) REFERENCES user(id),
--     FOREIGN KEY (aid) REFERENCES automata(id)
--
-- ) ENGINE=MyISAM  DEFAULT CHARSET=utf8;
